[package]
name = "heatc"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lib_heat_spec = { path = "../lib_heat_spec" }
clap = { version = "3.0.13", features = ["derive"] }
byteorder = "1"
